name: Publish Docker image

on:
  # 手動実行時
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: false
        default: "mseninc/blog-gatsby:latest"

  push:
    branches:
      - main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.event.inputs.tag || 'mseninc/blog-gatsby:latest' }}
