name: Publish Docker image

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tags: latest,main
