name: Prettier

on:
  push:
    branches:
      - main
      - 010-adjust-styles

jobs:
  format:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run Prettier
        run: npx prettier --write "**/*.{js,jsx,ts,tsx,json}"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prettier

